models:
  Client:
    company_name: string
    type: enum:Assistance,Insurance,Agency
    status: enum:Searching,Interested,Sent,Rejected,Active,On Hold
    initials: string:10
    number_requests: integer
    relationships:
      hasMany: Lead

  Lead:
    client_id: id foreign:clients
    email: string unique
    first_name: string
    status: enum:Introduction,Introduction Sent,Reminder,Reminder Sent,Presentation,Presentation Sent,Price List,Price List Sent,Contract,Contract Sent,Interested,Error,Partner,Rejected
    last_contact_date: date nullable
    relationships:
      belongsTo: Client

seeders: Client, Lead