<?php

namespace App\Filament\Support;

use App\Exports\ProviderBillsExport;
use App\Models\Bill;
use App\Models\Provider;
use App\Models\ProviderBranch;
use Filament\Tables;
use Filament\Tables\Columns\Column;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Str;
use Maatwebsite\Excel\Facades\Excel;

class BillTable
{
    /** @return list<string> */
    public static function eagerLoadRelations(): array
    {
        return [
            'file.patient',
            'file.serviceType',
        ];
    }

    public static function applyNameSearch(Builder $query, string $search): Builder
    {
        $search = addcslashes($search, '%_');

        return $query->where(function (Builder $inner) use ($search): void {
            $inner->where('bills.name', 'like', "%{$search}%")
                ->orWhereHas('file', function (Builder $fileQuery) use ($search): void {
                    $fileQuery
                        ->where('mga_reference', 'like', "%{$search}%")
                        ->orWhereHas('patient', fn (Builder $patientQuery) => $patientQuery->where('name', 'like', "%{$search}%"));
                });
        });
    }

    public static function nameSort(Builder $query, string $direction): Builder
    {
        return $query
            ->leftJoin('files', 'files.id', '=', 'bills.file_id')
            ->orderByRaw(
                "COALESCE(NULLIF(bills.name, ''), files.mga_reference) {$direction}",
            )
            ->select('bills.*');
    }

    public static function nameColumn(): Column
    {
        $search = fn (Builder $query, string $search): Builder => static::applyNameSearch($query, $search);

        return Tables\Columns\TextColumn::make('bill_label')
            ->label('Bill')
            ->state(fn (Bill $record): string => $record->display_name)
            ->searchable(true, $search)
            ->sortable(query: fn (Builder $query, string $direction): Builder => static::nameSort($query, $direction));
    }

    public static function relationManagerNameColumn(): Column
    {
        $search = fn (Builder $query, string $search): Builder => static::applyNameSearch($query, $search);

        return Tables\Columns\TextInputColumn::make('name')
            ->label('Bill')
            ->disabled(fn (Bill $record): bool => $record->hasCustomName())
            ->getStateUsing(fn (Bill $record): string => $record->hasCustomName() ? $record->name : '')
            ->placeholder(fn (Bill $record): string => $record->display_name)
            ->rules(['nullable', 'string', 'max:255'])
            ->updateStateUsing(function (Bill $record, ?string $state, $livewire): string {
                $bill = Bill::query()->with('file')->findOrFail($record->getKey());

                if ($bill->hasCustomName()) {
                    return $bill->name;
                }

                $fileReference = $bill->file?->mga_reference ?? '';
                $normalized = (! filled($state) || ($fileReference !== '' && Bill::matchesAutoGeneratedName($state, $fileReference)))
                    ? ''
                    : $state;

                $bill->update(['name' => $normalized]);

                if (method_exists($livewire, 'flushCachedTableRecords')) {
                    $livewire->flushCachedTableRecords();
                }

                return $bill->hasCustomName() ? $bill->name : '';
            })
            ->searchable(true, $search)
            ->sortable(query: fn (Builder $query, string $direction): Builder => static::nameSort($query, $direction));
    }

    public static function patientColumn(): Tables\Columns\TextColumn
    {
        return Tables\Columns\TextColumn::make('file.patient.name')
            ->label('Patient / DOB')
            ->searchable(['file.patient.name'])
            ->sortable()
            ->description(fn (Bill $record): string => $record->file?->patient?->dob?->format('d/m/Y') ?? '—');
    }

    public static function serviceColumn(): Tables\Columns\TextColumn
    {
        return Tables\Columns\TextColumn::make('file.service_date')
            ->label('Service / Type')
            ->date('d/m/Y')
            ->sortable()
            ->description(fn (Bill $record): string => $record->file?->serviceType?->name ?? '—');
    }

    public static function paymentColumn(): Tables\Columns\TextColumn
    {
        return Tables\Columns\TextColumn::make('paid_amount')
            ->label('Paid / Date / Status')
            ->money('EUR')
            ->sortable()
            ->description(function (Bill $record): string {
                $date = $record->payment_date?->format('d/m/Y') ?? '—';

                return "{$date} · {$record->status}";
            });
    }

    public static function totalColumn(): Tables\Columns\TextColumn
    {
        return Tables\Columns\TextColumn::make('total_amount')
            ->label('Total / Remaining')
            ->money('EUR')
            ->sortable()
            ->description(fn (Bill $record): string => 'Remaining: €' . number_format($record->remaining_amount, 2));
    }

    /** @return list<Column> */
    public static function relationManagerColumns(): array
    {
        return [
            static::relationManagerNameColumn(),
            static::patientColumn(),
            static::serviceColumn(),
            static::paymentColumn(),
            static::totalColumn(),
        ];
    }

    public static function configureRecordTitle(Tables\Table $table): Tables\Table
    {
        return $table->recordTitle(fn (Bill $record): string => $record->display_name);
    }

    public static function statusFilter(): Tables\Filters\SelectFilter
    {
        return Tables\Filters\SelectFilter::make('status')
            ->options([
                'Paid' => 'Paid',
                'Unpaid' => 'Unpaid',
                'Partial' => 'Partial',
            ])
            ->attribute('bills.status')
            ->query(function (Builder $query, array $data): Builder {
                $value = $data['value'] ?? null;

                if (blank($value)) {
                    return $query;
                }

                return $query->where('bills.status', $value);
            });
    }

    public static function exportAction(): Tables\Actions\Action
    {
        return Tables\Actions\Action::make('export')
            ->label('Export')
            ->icon('heroicon-o-arrow-down-tray')
            ->color('gray')
            ->action(function ($livewire) {
                $owner = $livewire->getOwnerRecord();
                $label = match (true) {
                    $owner instanceof Provider => $owner->name,
                    $owner instanceof ProviderBranch => $owner->branch_name,
                    default => 'bills',
                };

                $filename = 'bills_'.Str::slug((string) $label).'_'.now()->format('Y-m-d_H-i-s').'.xlsx';

                return Excel::download(
                    new ProviderBillsExport($livewire->getFilteredTableQuery()),
                    $filename
                );
            });
    }
}
